Lesson-1-9 Submission
Tugeeta/react-todo pull request #9
Opened 2023-06-11 02:35 UTC by Tugeeta

2023-06-11 02:36 UTC, Tugeeta commented
Package. JSON and Package.lock JSON also committed along with the Lesson-1-9

2023-06-12 14:24 UTC, XeniyaDob commented on src/App.js
> +        useEffect = (() => {
Please remove the extra `=` sign in the useEffect

2023-06-12 14:33 UTC, XeniyaDob commented on src/App.js
> +             console.log("Todos:", todos);
Take a look at how you receive the data object
<img width="660" alt="Screen Shot 2023-06-12 at 10 25 42 AM" src="https://github.com/Tugeeta/react-todo/assets/11164899/08ff8492-7bc4-4033-bf9e-28df925329da">

You don't need to capitalize the id and title properties of the todos obj. Use them exactly as you receive them in the data obj.

2023-06-12 14:41 UTC, XeniyaDob commented on src/App.js
>                const message = ('Error occurred: ${response.status}');
It looks like you have single quotes here instead of template literals.

2023-06-12 14:50 UTC, XeniyaDob requested changes
Great, you are almost there! 

I added a couple of comments to your Pull request files and also

 - Please `import React` in the `AddTodoForm.js` file.
 - You can delete the hardcoded `todoList` array in the `TodoList.js` file.

2023-06-14 02:01 UTC, merged